### ISSUE TITLE
mongodb version error 

### ISSUE THREAD

**Issue by wikumwicky** [Zeeshu911/MERN-Stack-Hospital-Management-System-Web-Application#4]
`/home/wikum/Desktop/MERN/backend/node_modules/bson/lib/bson.cjs:726
        inspect ??= defaultInspect;
                ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:992:16)
    at Module._compile (internal/modules/cjs/loader.js:1040:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/wikum/Desktop/MERN/backend/node_modules/mongodb/lib/bson.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
[nodemon] app crashed - waiting for file changes before starting...
`
![error](https://github.com/Zeeshu911/MERN-Stack-Hospital-Management-System-Web-Application/assets/121449684/a0dd0ea7-b53e-44cb-bd7f-cc7aadc9dca5)

**Comment by VinayakGaikwad101** [comment]
The ??= (nullish) operator is supported in Node.js versions 15 and above. You can upgrade your Node.js version to use this operator.

**Comment by satyam9721** [comment]
you need the white list current ip on mongo db atlas.

**Comment by vegansathya** [comment]
WHERE IS THE DOT ENV FILE IN THIS PROJECT

System-Web-Application\backend> npm start      
>> 

> backend@1.0.0 start
> node server.js

Some error occured while connecting to database: MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.createClient (C:\Users\NANDHINI\Desktop\hms\MERN-Stack-Hospital-Management-System-Web-Application\backend\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:206:11)
    at NativeConnection.openUri (C:\Users\NANDHINI\Desktop\hms\MERN-Stack-Hospital-Management-System-Web-Application\backend\node_modules\mongoose\lib\connection.js:801:34)
    at Mongoose.connect (C:\Users\NANDHINI\Desktop\hms\MERN-Stack-Hospital-Management-System-Web-Application\backend\node_modules\mongoose\lib\mongoose.js:404:15)
    at dbConnection (file:///C:/Users/NANDHINI/Desktop/hms/MERN-Stack-Hospital-Management-System-Web-Application/backend/database/dbConnection.js:5:6)
    at file:///C:/Users/NANDHINI/Desktop/hms/MERN-Stack-Hospital-Management-System-Web-Application/backend/app.js:37:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)    
    at async handleMainPromise (node:internal/modules/run_main:65:12)
Server listening at port undefined
